---
- hosts: vault
  gather_facts: yes
  roles:
    - role: hashivault
    - role: hashivault-init
    - role: hashivault-unseal
    - role: hashivault-pki-backend
    - { role: hashivault-unseal, do_it: 'again' }
